version: "3.7"

services:
  swag:
    image: ghcr.io/linuxserver/swag:4.2.0
    network_mode: host
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VALIDATION=http
      - URL=ptsteadman.com
      - TZ=America/New_York
    volumes:
      - ./swag-nginx-conf/default.conf:/config/nginx/site-confs/default.conf
      - ./src:/config/personal-website
      - /home/ubuntu/love-poem:/config/love-poem
      - /home/ubuntu/memorial:/config/memorial
    restart: always
